### ISSUE TITLE
Clarify relationship between AWS_S3_KEY_PREFIX and AWS_S3_PUBLIC_URL

### ISSUE THREAD

**Issue by cassandra** [etianen/django-s3-storage#118]
When using both AWS_S3_KEY_PREFIX and AWS_S3_PUBLIC_URL, I am finding that there is a dependency and the url setting must include the prefix also.  I do not know if that is by design or not, but before I begin to depend on this behavior, wanted to check that it is working as expected. I do not see anywhere in the code an attempt to add the prefix to this url.

If this is expected behavior, then a doc update to clarify would help.  If not expected, and this behavior may change in the future, then my config will break and hence my wanting to get some clarity before proceeding.

(Thank you for creating and maintaining this module BTW. Very helpful.)

**Comment by etianen** [comment]
The trouble is, it's a bit complicated.

AWS_S3_KEY_PREFIX is "a prefix to apply to every key when saving it to a
bucked"
AWS_S3_PUBLIC_URL is "a prefix to apply to every key when generating URLs"

If you don't provide AWS_S3_PUBLIC_URL, it'll use direct S3 URLs.
AWS_S3_PUBLIC_URL is there to allow you to use a CDN or other form of
proxy, like cloudflare, cloudfront etc.

Now, in most sane setups, there's a strong relationship between the two. If
you prefix all your keys with /foo/, it's likely that all your URLs will
want to look like https://some-domain/foo/. After all, you're just mapping
the domain of your CDN with the domain of your S3 bucket, and the path
component of the URL is just proxied through.

BUT, there's nothing stopping you writing an nginx reverse proxy that, say,
maps https://some-domain/*foo/* to https://some-bucket/*bar/ *. It would be
weird, but I'm sure some scrum master somewhere would find a reason it made
sense.

So that leaves us here. In most sane setups, there is a strong relationship
between AWS_S3_KEY_PREFIX and AWS_S3_PUBLIC_URL. But there's no such
relationship *inherent* in django-s3-storage, and there never will be
without a breaking change.

I'm not sure we need any documentation of this besides this issue (too much
documentation is as bad as too little). As always though, test your code
after upgrading libraries!

**Comment by cassandra** [comment]
I had not thought about the proxy case where it might be desirable to decouple the prefix and URL, so it makes sense the way it is designed.  A small note is all I think is needed to help, at least it would have helped me. Maybe in the docs for AWS_S3_PUBLIC_URL, say something like "If also using AWS_S3_KEY_PREFIX, this url may need to include the prefix."
