### ISSUE TITLE
Upload files to "." directory

### ISSUE THREAD

**Issue by frederikbotha** [etianen/django-s3-storage#18]
Hi,

Not sure if this is an issue or me setting things up wrong...most likely the latter. I really don't know where else to ask for support, I've tried IRC #django but did not really get anywhere.

I have it setup with private file upload and static storage and it works as expected, except for the private upload bit. It upload everything to a directory in the bucket called "." so it would be; bucketname/./filethatwasuploaded
I am not sure why or how to get it to upload just to the bucket, I've tried putting in a prefix, but then i get bucketname/prefix/./filethatwasuploaded

I am using:
Django==1.9.6
boto==2.40.0
django-s3-storage==0.9.8

The settings in the settings file is almost identical to the ones in the readme, except for the keys.

Any help would be very much appreciated and thanks for a great package.

**Comment by etianen** [comment]
Ah, so django-s3-storage normalizes the path before upload. I suspect that
the dot is being stripped as part of path normalisation.

The answer here is probably "don't do that". Consider a prefix such as
".private/" if you really must have a dot in the path name.

**Comment by frederikbotha** [comment]
I am not adding the ".", I am trying to get rid of the dot. I upload a file and it creates a directory in s3 called "." and add my file in that directory. If I add a prefix of say "private", my file will be uploaded to "private/./filename".

**Comment by frederikbotha** [comment]
I found the problem and embarrassingly it was me not putting upload_to in the model (facepalm), so django-s3-storage create a directory called "."
Sorry and thanks for your replies.

**Comment by etianen** [comment]
Hmm, interesting side-effect. I'd have sworn that Django used to require
specifying upload_to. Maybe that's changed.

Still, good to know!

**Comment by paulfurley** [comment]
Bizarrely I have just encountered this exact problem, but it manifested itself in this tricky AWS signature validation error:
![image](https://cloud.githubusercontent.com/assets/254290/15542256/dcafad0c-2287-11e6-8646-0b337aed4b7e.png)

**Comment by paulfurley** [comment]
OK, I've now confirmed that if you don't specify `upload_to` on your `FileField` then you get bad AWS signatures.

In the case where `upload_to` is unset, I think this is happening:

- The file is uploaded to the incorrect location `/<bucket>/<key prefix>/./<filename>` (as per @frederikbotha's original report)
- BUT the `generate_url` signed request is for the *correct* URL `/<bucket>/<key prefix>/<filename>`

And thus the signature doesn't match.

When I set `upload_to="files"`, it fixed it because files are now uploaded to `/<bucket>/<key prefix>/files/<filename>` and signed requests are for that same location.

**Comment by etianen** [comment]
It feels like django-s3-storage SHOULD be normalizing these paths before AWS sees them. Hmm, I thought it was. This needs investigation.

Meanwhile, the work-around is to actually set upload_to.

**Comment by paulfurley** [comment]
Thanks @etianen, and thanks for this great library!

**Comment by frederikbotha** [comment]
Yeah thanks for a great library and a quick response

**Comment by paulfurley** [comment]
Brilliant, thanks!

**Comment by gcbirzan** [comment]
Any chance for a pypi upload?

**Comment by etianen** [comment]
pypi was down this morning, so I was gonna wait until this evening. Still,
I've just had another go, and it works now, so it's up!

**Comment by etianen** [comment]
Aha, so it turns out that #20 actually introduced a regression, where existing S3 keys including special characters like `.` became impossible to access.

I've pushed a new commit to master that should fix the bug described here, without causing existing keys to break. It would be good if someone could confirm that the master branch still fixes this issue, before I bake it into a new release.

**Comment by etianen** [comment]
Commit was 893608027e8a78dc9b57f783d0c21541cbd2dad2 , for the interested.

**Comment by leonsmith** [comment]
Apologies, Is it worth getting in a regression test?
I could take a look tonight and also test out that 8936080 commit as well

**Comment by etianen** [comment]
No worries, I also looked over the code, and didn't see anything wrong!
It's my bug too! :P Verification that the new patch still solves your issue
would be good, however. :)

A simple regression test might be worthwhile. I'm always cautious of
uncontrolled test proliferation though, as past a certain point the test
suite starts becoming unwieldy and scary to touch.
