### ISSUE TITLE
Not compatible with django = 1.10.1

### ISSUE THREAD

**Issue by Eracleo** [etianen/django-s3-storage#32]
No storage images in bucket with django =1.10.1, I test in local and prod (apache2.4)
Not show any errors.

Every things is ok, but the image not store in bucket, But when I change django to 1.10 is ok

When I create a file in my bucket Django==1.10.1, every things is ok.
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.core.cache import cache

> > > default_storage.exists('storage_test')
> > > False
> > > file = default_storage.open('storage_test', 'w')
> > > file.write('storage contents')
> > > file.close()
> > > default_storage.exists('storage_test')
> > > True

(my first issues)

**Comment by etianen** [comment]
I'm afraid I can't reproduce this issue. django-s3-storage is tested on
Django 1.10.1, and works fine.

https://travis-ci.org/etianen/django-s3-storage/builds/162724170

Are you certain that it works with 1.10, but not 1.10.1? Could you test it
again? Otherwise, I'm going to need an example of failing behaviour to
debug this further.
