### ISSUE TITLE
Why should I use django-s3-storage instead of django-storages-redux?

### ISSUE THREAD

**Issue by aaugustin** [etianen/django-s3-storage#4]
I would find it useful to address this question in the README.

Perhaps you just wrote django-s3-storage because it was fun.

Perhaps you wanted a library that did one thing and did it well. django-storages clearly exihibits kitchen sink syndrome.

Perhaps you wanted a modern and well-documented library. django-storages was abandoned and revived as django-storages-redux; it shows.

Perhaps you needed features that django-storages-redux didn't provide.

I'm interested in trying alternatives to the current _de facto_ solution. It would be an easier decision if I knew why the alternative exists!

Thanks!

**Comment by etianen** [comment]
To answer your question:

1. I needed Python3 support, and didn't know that django-storages-redux existed at the time.
2. I wanted to use different buckets for static and media files.
3. Philosophically, a project should do one thing well, not attempt to be a solution for *all* storage backends.

I was reluctant to write this in the README, since it inherently requires criticising another person's work. The original django-storages was a bit of a mess, and I hit a few bugs with gzip compression of files. I didn't trust it, and I needed to move to Python 3 anyway.

How would you suggest documenting this in a non-confrontational way?

**Comment by aaugustin** [comment]
Here's how I would write it.

### How does django-s3-storage compare with django-storages?

The [django-storages-redux](https://github.com/jschneier/django-storages) fork of django-storages appears to be the most widely used S3 storage backend for Django. It also supports a variety of other storage backends.

django-s3-storage provides similar features but only supports S3. It was originally written to support Python 3 at a time when the future of django-storages was unclear.

The author of django-s3-storage is not aware of significant differences in functionality with django-storages-redux. If you notice some differences, please file an issue!

**Comment by etianen** [comment]
You should be a politician. I'll add this in tomorrow. :)

**Comment by aaugustin** [comment]
FYI I just found a situation where django-s3-storages outperforms django-storages: https://github.com/jschneier/django-storages/issues/95

**Comment by etianen** [comment]
Woo! Not Invented Here FTW! :D
