### ISSUE TITLE
File name should use forward slash even in Windows

### ISSUE THREAD

**Issue by ceefour** [etianen/django-s3-storage#67]
I'm using `ImageField` and `django-imagekit` with django-s3-storage and I noticed that file `name` of a `ImageField/FileField` is using Windows path separators, e.g.

```
"photo_id": "family-child\\26-abu-bakar.jpg",
"photo_url": "https://s3.amazonaws.com/media.keluargasamara.com/prd/family-child/26-abu-bakar.jpg",
"thumbnail_id": "CACHE\\images\\family-child\\26-abu-bakar\\352a50472bc938d5e792c202401046be.jpg",
"thumbnail_url": "https://s3.amazonaws.com/media.keluargasamara.com/prd/CACHE/images/family-child/26-abu-bakar/352a50472bc938d5e792c202401046be.jpg",
```

Note that I recently migrated from `django-storages` due to [this bug](https://github.com/matthewwithanm/django-imagekit/issues/391#issuecomment-306754822). django-storages properly used forward slash, but it made django-imagekit unusable (For now).

I presume that this bug doesn't occur on Linux OS but the behavior should be consistent on Windows, because these paths are **S3 paths, they're not Windows paths**.

**Comment by etianen** [comment]
I've just pushed a fix to master. Let me know if it works.

Importantly, it's worth noting here that django-s3-storage has always converted windows paths to posix paths when saving files. However, this wasn't reflected in the return value of `save()` It didn't really matter, because passing the windows-style path to django-s3-storage would always normalize to the correct S3 key name.

The patch I've pushed simply ensures that `save()` normalizes the path to posix form.
